export const FETCH_FEATURED_STREAMS_SUCCESS = 'FETCH_FEATURED_STREAMS_SUCCESS';
export type FETCH_FEATURED_STREAMS_SUCCESS = typeof FETCH_FEATURED_STREAMS_SUCCESS;
export const FETCH_FEATURED_STREAMS_ERROR = 'FETCH_FEATURED_STREAMS_ERROR';
export type FETCH_FEATURED_STREAMS_ERROR = typeof FETCH_FEATURED_STREAMS_ERROR;
export const FETCH_FEATURED_STREAMS_LOADING = 'FETCH_FEATURED_STREAMS_LOADING';
export type FETCH_FEATURED_STREAMS_LOADING = typeof FETCH_FEATURED_STREAMS_LOADING;
