export const FETCH_FOLLOWED_STREAMS_SUCCESS = 'FETCH_FOLLOWED_STREAMS_SUCCESS';
export type FETCH_FOLLOWED_STREAMS_SUCCESS = typeof FETCH_FOLLOWED_STREAMS_SUCCESS;
export const FETCH_FOLLOWED_STREAMS_ERROR = 'FETCH_FOLLOWED_STREAMS_ERROR';
export type FETCH_FOLLOWED_STREAMS_ERROR = typeof FETCH_FOLLOWED_STREAMS_ERROR;
export const FETCH_FOLLOWED_STREAMS_LOADING = 'FETCH_FOLLOWED_STREAMS_LOADING';
export type FETCH_FOLLOWED_STREAMS_LOADING = typeof FETCH_FOLLOWED_STREAMS_LOADING;
