
export const FETCH_LIVE_STREAMS_SUCCESS = 'FETCH_LIVE_STREAMS_SUCCESS';
export type FETCH_LIVE_STREAMS_SUCCESS = typeof FETCH_LIVE_STREAMS_SUCCESS;
export const FETCH_LIVE_STREAMS_ERROR = 'FETCH_LIVE_STREAMS_ERROR';
export type FETCH_LIVE_STREAMS_ERROR = typeof FETCH_LIVE_STREAMS_ERROR;
export const FETCH_LIVE_STREAMS_LOADING = 'FETCH_LIVE_STREAMS_LOADING';
export type FETCH_LIVE_STREAMS_LOADING = typeof FETCH_LIVE_STREAMS_LOADING;
